dnf install -y \
  gcc gcc-c++ make cmake \
  git python3 python3-pip \
  pkgconfig \
  glib2-devel \
  gtk3-devel \
  nss-devel \
  nspr-devel \
  cups-devel \
  dbus-devel \
  atk-devel \
  at-spi2-atk-devel \
  alsa-lib-devel \
  pulseaudio-libs-devel \
  libXtst-devel \
  libXrandr-devel \
  libXScrnSaver-devel \
  libXcursor-devel \
  libXdamage-devel \
  libXi-devel \
  libXcomposite-devel \
  mesa-libGL-devel \
  mesa-libEGL-devel \
  pango-devel \
  cairo-devel \
  fontconfig-devel \
  freetype-devel \
  harfbuzz-devel \
  libxkbcommon-devel \
  wayland-devel \
  libdrm-devel \
  bzip2-devel \
  zlib-devel \
  libcap-devel \
  libgcrypt-devel \
  libjpeg-turbo-devel \
  flac-devel \
  speech-dispatcher-devel \
  perl \
  bison \
  gperf \
  ninja-build \
  nodejs \
  java-latest-openjdk-headless \
  which \
  curl \
  rsync \
  xz \
  binutils